version: '3.9'
services:
  db:
    image: postgres:16
    container_name: pg-ledger
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: .
    container_name: ledgerpro-api
    environment:
      DB_URL: jdbc:postgresql://db:5432/appdb
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: ${JWT_SECRET:-VGhpcy1pcy1hLXN1cGVyLXNlY3JldC1zZWVkLWF0LWxlYXN0LTI1Ni1iaXRzIQ==}
      TZ: UTC
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  ui:
    build:
      context: ./ui
    container_name: ledgerpro-ui
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  pgdata:
